const fs = require('fs');
const path = require('path');
const { parseEnv } = require('./parser');

/**
 * Generate a safe dummy value for a given key
 */
function getPlaceholderValue(key, originalValue) {
  const upper = key.toUpperCase();

  // Safe common keys to keep or provide standard defaults
  if (upper === 'NODE_ENV') return 'development';
  if (upper === 'PORT') return originalValue && !isNaN(originalValue) ? originalValue : '3000';
  if (upper === 'HOST') return 'localhost';
  if (upper === 'DEBUG') return 'false';
  if (upper === 'LOG_LEVEL') return 'info';
  if (upper === 'APP_ENV') return 'local';
  if (upper === 'TZ') return 'UTC';

  // Database URLs
  if (upper.includes('DATABASE_URL') || upper.includes('DB_URL')) {
    return 'postgresql://user:password@localhost:5432/my_database';
  }
  if (upper.includes('MONGO_URI') || upper.includes('MONGODB_URI')) {
    return 'mongodb://localhost:27017/my_database';
  }
  if (upper.includes('REDIS_URL')) {
    return 'redis://localhost:6379';
  }

  // Common credentials
  if (upper.includes('SECRET') || upper.includes('KEY') || upper.includes('TOKEN')) {
    return `your_${key.toLowerCase()}_here`;
  }
  if (upper.includes('PASSWORD') || upper.includes('PASS') || upper.includes('PWD')) {
    return 'your_password_here';
  }
  if (upper.includes('EMAIL') || upper.includes('USER')) {
    return `your_${key.toLowerCase()}@example.com`;
  }
  if (upper.includes('URL') || upper.includes('ENDPOINT')) {
    return 'https://api.example.com';
  }

  return `your_${key.toLowerCase()}_here`;
}

/**
 * Generates .env.example content from an existing .env file
 */
function generateExample(sourcePath, targetPath, options = {}) {
  const { entries } = parseEnv(sourcePath);
  const outputLines = [
    '# =========================================================================',
    '# Auto-generated by EnvShield (https://github.com/bipinone/envshield)',
    '# Safe template file: Do NOT put real secrets or credentials here!',
    '# =========================================================================',
    ''
  ];

  for (const entry of entries) {
    if (entry.type === 'empty') {
      outputLines.push('');
    } else if (entry.type === 'comment') {
      outputLines.push(entry.raw);
    } else if (entry.type === 'var') {
      const placeholder = getPlaceholderValue(entry.key, entry.value);
      const commentPart = entry.comment ? ` ${entry.comment}` : '';
      outputLines.push(`${entry.key}=${placeholder}${commentPart}`);
    }
  }

  const content = outputLines.join('\n') + '\n';

  if (targetPath) {
    fs.writeFileSync(targetPath, content, 'utf-8');
  }

  return content;
}

module.exports = {
  generateExample,
  getPlaceholderValue
};
